name: Build the LaTeX template

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: template.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Template
          path: template.pdf
      - name: Push changes
        run: |
          git add template.pdf
          git commit -m "chore(codebase): format with black"
          git push