name: Build the LaTeX template

on:
  push:
    branches:
      - main

env:
  VERSION_FILE: NOVAthesisFiles/nt-version.sty
  ROW_VERSION: 1
  VERSION_START_POS: 33

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version
        run: |
          versionrow=$(head -n$ROW_VERSION $VERSION_FILE)
          version="${versionrow:$VERSION_START_POS:-1}"
          echo $version
      - name: Compile the LaTeX template
        uses: xu-cheng/latex-action@v2
        with:
          root_file: template.tex
      - name: Upload the PDF template file
        uses: actions/upload-artifact@v3
        with:
          name: Template
          path: template.pdf
      - name: Push changes to the repository
        run: |
          git config --global user.email "joao.lourenco@fct.unl.pt"
          git config --global user.name "joaomlourenco"
          git add template.pdf
          git commit -m "Version $version"
          git push